FROM node:16

ARG DATABASE_URL=postgresql://winter@localhost:5432/blog
ARG PORT=3000
ENV DATABASE_URL ${DATABASE_URL}

WORKDIR /usr/src/app

COPY package.json yarn.lock ./
COPY db/ ./db/
RUN yarn install --frozen-lockfile

COPY . .
RUN yarn build

EXPOSE ${PORT}

CMD sh ./bin/start.sh