version: "3.7"

services:
  db:
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data
    container_name: db
    env_file: ./.env.production
    ports:
      - "5432:5432"
    restart: always
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: app
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always
volumes:
  data:
